NXBT-341: Change ownership of data dir during migration
--HG--
branch : 1.0

diff --git a/resources/static_lib/internal/migrate-from-pre55 b/resources/static_lib/internal/migrate-from-pre55
--- a/resources/static_lib/internal/migrate-from-pre55
+++ b/resources/static_lib/internal/migrate-from-pre55
@@ -175,6 +175,17 @@ if [ "$MOVE_DATA_DIR" = "true" ]; then
             exit 1
         fi
     fi
+else
+    if [ "$DRY_RUN" = "true" ]; then
+        echo "Not changing ownership of @nuxeo.data.dir@: dry run"
+    else
+        chown -R @package.name.clean@:@package.name.clean@ "@nuxeo.data.dir@"
+        if [ "$?" != "0" ]; then
+            echo "Failed to grant ownership of @nuxeo.data.dir@ to the @package.name.clean@ user."
+            echo "Package(s) data may be in an inconsistent state."
+            exit 1
+        fi
+    fi
 fi
 
 # Replace things in the config file
